filebeat.inputs:
  - type: filestream
    id: docker-logs
    paths:
      - /var/lib/docker/containers/*/*.log
    parsers:
      - ndjson:
          overwrite_keys: true
    processors:
      - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]
