input {
  beats {
    port => 5044
  }
}

filter {
  if [fileset][module] == "docker" {
    json { source => "message" target => "json" skip_on_invalid_json => true }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
}
