{
 "title": "EduFeed — HTTP & Logs",
 "tags": [
  "edufeed",
  "http"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request rate (req/s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "5xx per second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{status=\"500\"}[5m]))"
    }
   ]
  },
  {
   "title": "HTTP p95 latency (s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_server_requests_seconds_bucket[5m])))"
    }
   ]
  },
  {
   "title": "Requests by status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_server_requests_seconds_count[1m]))"
    }
   ]
  },
  { "title": "Logs", "type": "logs", "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 } }
 ]
}